import Image from "next/image";

export const Heading1 = {
  title: "Board of trustees",
  description:
    "The Board of Trustees is responsible for safeguarding the interests of the Association. ",
  decorativeImage: "/images/our-team/swish.svg",
};

export const Heading2 = {
  title: "Associate Founders",
  description:
    "The Associate Founder provides crucial support to the Founder's vision and objectives.",
  decorativeImage: "/images/our-team/swish.svg",
};

export const Heading3 = {
  title: "Executives",
  description:
    "The executive members are the engine of the association, doing all the implementation tasks in various capacities ",
  decorativeImage: "/images/our-team/swish.svg",
};

export const BoardOfTrustees = [
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Prof.-Mnguember-Vicky-Sylvester.png",
    role: "Secretary",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Prof. Mnguember Vicky Sylvester ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Kema-Chikwe.png",
    role: "Member",
    biolink: "Kema Chikwe",
    fullName: " Dr. Kema Chikwe ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Hassan-Mahmud.png",
    role: "Member",
    biolink: "Hassan-Mahmud",
    fullName: " Dr. Hassan Mahmud ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Hassana-Abdullahi.png",
    role: "Member",
    biolink: "Hassana-Abdullahi",
    fullName: "Dr. Hassana Abdullahi",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Nkem-Okeke.png",
    role: "Member",
    biolink: "Nkem-Okeke",
    fullName: " Dr. Nkem Okeke",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Mnguember-Vicky-Sylvester.png",
    role: "Member",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Prof. Mnguember Vicky Sylvester ",
  },
];

export const AssociateFounders = [
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Chioma-Ikeanyionwu.png",
    role: "Excellent  Performance Hunt Coordinator",
    biolink: "Chioma-Ikeanyionwu",
    fullName: " Prof. Chioma Ikeanyionwu ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Ngozi-Eunice-Egbuna.png",
    role: "Event and Compliance Coordinator)",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: "Prof. Ngozi Eunice Egbuna ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Chineye-Viola-Udeze.png",
    role: "Research Coordinator",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Prof. Chinenye Viola Udeze ",
  },
];

export const Executives = [
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Adaeze-Patricia-Esenwah.png",
    role: "Founder/President",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Dr. Adaeze Patricia  Esenwah ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Anastasia-Eruaga.png",
    role: "Vice President & Legal Advisor ",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Dr.  Osatohanmwen Osamudiamen Anastasia Eruaga ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Sarah-Ogah-Aduwari.png",
    role: "Secretary",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: "Dr. Sarah Ogah-Aduwari ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Hadiza-Minna.png",
    role: "Assistant Secretary General",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Dr. Hadiza Minna ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Princess-Enape-Victoria-Ayishetu.png",
    role: "Financial Secretary",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Dr. Princess Enape Victoria Ayishetu ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Victoria-Afangideh.png",
    role: "Treasurer",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Dr Victoria Afangideh ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Ngozi-Cordelia-Agbata.png",
    role: "Provost",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Dr. Ngozi Cordelia Agbata ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Victoria-Oladumeji.png",
    role: "Public Relations Officer",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: " Dr. Victoria Oladumeji ",
  },
  {
    biodata:
      "Kema Chikwe was born to Mr. Nathan Ejiogu from Egbu, Owerri in Imo State and Mrs Amelia Ejiogu.  She attended Queen’s College, Lagos, and Queen’s School, Enugu, for her secondary education and Advanced Teachers Training College, Owerri, before she proceeded to Queens College, City University of New York, where she obtained Bachelor's and Master's degrees in French. She earned her Doctorate Degree in Curriculum Education in 1995 from the University of Nigeria, Nsukka. Dr. Chikwe is a distinguished public administrator, educationist, gender and social engineer, activist, writer, and diplomat. Dr. Chikwe’s dynamism especially came to the fore when she was appointed as the Minister of Transport in the cabinet of former President Olusegun Obasanjo following Nigeria’s return to democracy in 1999. As Minister of Transport, Dr. Chikwe presided over 20 Federal Government parastatals, including the Nigerian Ports Authority, National Maritime Authority, Nigeria Inland Waterways Authority, and so on. Thus, Dr. Chikwe significantly became the first woman to be appointed as the head of a major infrastructure ministry.  She was later moved to the Ministry of Aviation as the first female Minister of Aviation between 2000 and 2003, where she recorded no fewer sterling achievements in her new assignment. Between 2005 and 2006, Dr. Chikwe served as the first female Chairman of Joint Admission and Matriculations Board, JAMB.  Dr. Chikwe was appointed Nigeria’s Ambassador to Ireland and Iceland in 2008. Between 2008 and 2011 Dr. Chikwe founded the Women’s Leadership Institute. Women's Leadership Institute (WLI) is an international leadership development organization. WLI provides a professional and non-partisan platform for women in Nigeria and across Africa to develop their leadership capacity and to take on constructive roles in the political and economic development of Nigeria and Africa in general. WLI offers vocational training, executive leadership programs, customized leadership interventions, and classroom-based leadership development courses in three categories: certificate, diploma, and advanced leadership courses. Dr. Chikwe is a renowned writer; her books are included in both the Nigerian and American curricula. The books include Kema Chikwe: Across Borders, Women of My Era, Village Boys, First School Day for Adaze, Kame Chameleon Tours the Garden, My Precious Book, and other publications. Her NGO-Women and A New Orientation, continues to empower women nationwide. Her goal is to relentlessly work towards tireless change, especially concerning women in Nigeria. Dr. Kema Chikwe, a life member of NCWS, once served as the Secretary of Imo State NCWS and in other capacities on the State and National levels. Currently, she is a member of the board of trustees at the national level. Dr. Kema Chikwe is married to Chief (Nze) Herbert Chikwe, a successful businessman.  They are blessed with five children and eighteen grandchildren.",
    src: "/images/our-team/Obiamaka-Clara-Itanyi.png",
    role: "PRO 2 & IT Manager",
    biolink: "Mnguember-Vicky-Sylvester",
    fullName: "Dr. Obiamaka Clara Itanyi ",
  },
];
